title: Ricardo Jimenez Pina
logo: docs/assets/portfolioimageofme.png
description: Mechanical Engineering Student | Construction Specialist | Structural Builder
#show_downloads: true
theme: jekyll-theme-minimal 
